name: .NET Core Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Run automatized tests
      run: dotnet test ${{ secrets.TEST_PROJECT_PATH }} --verbosity minimal

    - name: Build with the dotnet utility
      run: dotnet build ${{ secrets.WEBAPP_PROJECT_PATH }} --configuration Release

    - name: Publish with the dotnet utility
      run: dotnet publish ${{ secrets.WEBAPP_PROJECT_PATH }} -c Release -o app

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure App Service Deployment
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEBAPP_AZURE_NAME }}
        package: './app'
